### ISSUE TITLE
In Vegacapsule the logs are outputed to `stderr` instead of `stdout`

### ISSUE THREAD

**Issue by zale144** [vegaprotocol/liqbot#178]
Since the beginning, the `liqbot` has been using `logrus` as the 3rd party logger. In the context of liqbot logging, out-of-the-box configuration ends up having the logs written to `stderr` instead of `stdout`. The solution is probably replacing `logrus` with Vega standard logger (wrapper for `uber.zap`).

**Comment by gordsport** [comment]
closed in
