### ISSUE TITLE
Bots should not top-up very often - ensuring balance overhead should be reduced

### ISSUE THREAD

**Issue by zale144** [vegaprotocol/liqbot#181]
If the bot has insufficient funds to place an order or provide liquidity, it asks for funds from a `whale` service. However, if it asks for a top-up each time it places an order, it will be a significant overhead. To reduce this overhead, the logic should be as such:
- If the funds are sufficient for the transaction, no need to top up,
- If the funds are less than needed for a transaction, ask for a top-up from the whale, for the `amount * scale`, where scale is an arbitrary number that we multiply the ensured amount with, in order to avoid frequent top-ups.

**Comment by gordsport** [comment]
closed in https://github.com/vegaprotocol/liqbot/issues/189
