### ISSUE TITLE
Placing orders errors with `not enough funds`

### ISSUE THREAD

**Issue by zale144** [vegaprotocol/liqbot#184]
Even after a successful top-up, the order placement is rejected with `not enough funds` error. The cause is likely a decimal place difference between the account balance, which is expressed in Asset original decimal places, and the order cost, which is expressed in the market decimal places. Typically, the number of market decimal places is lower than the asset number of decimal places.

**Comment by gordsport** [comment]
closed in https://github.com/vegaprotocol/liqbot/issues/189
