### ISSUE TITLE
REST API: add endpoints

### ISSUE THREAD

**Issue by ashleyvega** [vegaprotocol/liqbot#22]
## Endpoints
- `GET /status` - return a fixed `{"success":true}` so the service can be monitored
- `GET /traders-settlement` (json key names copied from https://test-bots.ops.vega.xyz/traders-settlement)

  ```json5
  [
    {
      "name": "b00", // name of bot, from config file. not used, but nice to see
      "pubKey": "d2...34",
      "settlementEthereumContractAddress":"0x65...4d"
    },
    // ...
  ]
  ```

**Comment by edd** [comment]
Expansion after discussion on Slack, also:  

- PUT `/start` - Start paused bots
- PUT `/stop` - Stop bots trading
