### ISSUE TITLE
Upgrade the price moving logic to the version supplied by David

### ISSUE THREAD

**Issue by peterbarrow** [vegaprotocol/liqbot#32]
Add back in the logic that will steer the price towards an external price value

**Comment by davidsiska-vega** [comment]
This is the relevant part from the spec. 
### Create markets that look real
This section is only relevant if the bot is configured with a price source providing a reference price.

Place good till time limit orders of some duration near the reference price consistently with `targetLNVol` according to `limitOrderDistributionParams`. 

Example:
```
limitOrderDistributionParams = { 
    method = "dicreteThreeLevel"
    gttLengh = "60s"
    tgtTimeHorizon = "1 hour"
    tickSize = 0.01
    numTicksFromMid = 5
    tgtOrdersPerSecond = 2
    numIdenticalBots = 3
}
```
With the above example you can generate the correct orders using the method in the [notebook](./BotParameterCalcAndTest.ipynb) with `delta=tickSize x numTicksFromMid` and `N = 3600 x 2 / 3`.

Another Example:
```
limitOrderDistributionParams = { 
    method = "coinAndBinomial"
    gttLengh = "60s"
    tgtTimeHorizon = "1 hour"
    tickSize = 0.01
    numTicksFromMidMax = 5 // nMoves in IPython notebook
    tgtOrdersPerSecond = 0.5 // i.e. one order every 2 seconds
    numIdenticalBots = 10
}
```

Again, the algorithm for choosing the parameters and generating samples is in the [notebook](./BotParameterCalcAndTest.ipynb) with `delta=tickSize x numTicksFromMid` and `N = 3600 x 0.5 / 10`. 

Whoever gets to implement this - if the Python notebook isn't good enough to explain what's going on then ping me and I'll try to help.

**Comment by peterbarrow** [comment]
Added as part of PR #46
