### ISSUE TITLE
Make liqbot survive back-end node restart

### ISSUE THREAD

**Issue by ashleyvega** [vegaprotocol/liqbot#36]
When a Veganet is restarted, liqbot does not like it, and becomes unable to submit any orders:

```
Apr 27 10:34:25 vega-bot-1 liqbot[3632194]: 
time="2021-04-27T10:34:25.785852911Z" 
level=warning 
msg="Error during price steering" 
bot=b00 
error="failed to sign and submit tx: failed to submit signed tx: gRPC call failed: 
    SubmitTransaction: rpc error: code = InvalidArgument desc = InvalidArgument error" 
node="n04.d.vega.xyz:3002" 
pubkey=22...f4 
sleepTime=29000
```

## Tasks
- [x] Improve general error handling to get all the gRPC error detail, not just "internal error" or InvalidArgument. - done already
- [ ] Make liqbot capable of surviving a restart of the gRPC node(s) it's connected to.

**Comment by peterbarrow** [comment]
I started doing some work on this but realised during testing that when I restarted a node the market would have a different marketID. How would the bot go about getting the new value to continue running?

**Comment by ashleyvega** [comment]
@peterbarrow At the moment we assume persistent Market IDs.

We could switch to specifying the market by:
* `market.tradableInstrument.instrument.code`, e.g. `BTCUSD.MF21`
* `market.tradableInstrument.instrument.metadata.tags`, e.g. `base:BTC` and `quote:USD` (and any other tags to narrow down the list)

If the resulting market list is empty, then log an error and end the goroutine(s) for the bot. If the resulting market list is longer than one, then pick the first entry, or a random one.

**Comment by peterbarrow** [comment]
Does the assumption that the Market IDs stays the same carry on to the partyIDs too?
I'm thinking about after a veganet restart does it have the same users defined?

**Comment by ashleyvega** [comment]
thinking about partyIDs:
- when dockerisedvega is restarted, a new set of N wallets + pubkeys is generated, so partyIDs for those auto-generated wallets all change
- when running liqbot (and the same goes for traderbot), it uses an internal wallet, with the wallet files saved to disk, so when restarting liqbot, none of the partyIDs change

When a Vega network is restarted, all the party account balances go to zero. But liqbot is still running its goroutines and trying to check account balances and submit orders. liqbot should see that it's got no money and wait quietly til it can continue.
