### ISSUE TITLE
Add auction support

### ISSUE THREAD

**Issue by edd** [vegaprotocol/liqbot#7]
If the bot has `currentPrice` then it should place  buy / sell limit orders (good till time with duration a bit longer than opening auction length) in the auction at random distance and volume away from `currentPrice` up to total `auctionVolume`. 
The distance and volume should be consistent with market risk parameters

**Comment by davidsiska-vega** [comment]
If the market is in an auction mode then the bot shouldn't place market orders to manage its position.
