### ISSUE TITLE
Support external price feeds

### ISSUE THREAD

**Issue by edd** [vegaprotocol/liqbot#8]
This section is only relevant if the bot is configured (#5) with a price source providing a reference price.

Place good till time limit orders of some duration near the reference price consistently with `targetLNVol` according to `limitOrderDistributionParams`. 

Example:
```
limitOrderDistributionParams = { 
    method = "dicreteThreeLevel"
    gttLengh = "60s"
    tgtTimeHorizon = "1 hour"
    tickSize = 0.01
    numTicksFromMid = 5
    tgtOrdersPerSecond = 2
    numIdenticalBots = 3
}
```

Another Example:
```
limitOrderDistributionParams = { 
    method = "coinAndBinomial"
    gttLengh = "60s"
    tgtTimeHorizon = "1 hour"
    tickSize = 0.01
    numTicksFromMidMax = 5 // nMoves in IPython notebook
    tgtOrdersPerSecond = 0.5 // i.e. one order every 2 seconds
    numIdenticalBots = 10
}
```

Generate the orders using the above method *but*:
- If the position of the bot is long *only* place sell orders. 
- If the position of the bot is short *only* place buy orders here. 

See: [vegaprotocol/priceproxy](https://github.com/vegaprotocol/priceproxy)

**Comment by ashleyvega** [comment]
Done in https://github.com/vegaprotocol/liqbot/tree/develop/pricing/

Configured with:
```yaml
pricing:
  address:
    scheme: https
    host: prices.ops.vega.xyz
    path: /prices
```
